Regularization fix
AlexPasqua/NNs-from-scratch pull request #43
Opened 2020-12-24 19:12 UTC by gaetanoantonicchio

Implemented l1 and l2 regularization: func and deriv

2020-12-24 20:13 UTC, AlexPasqua reviewed
- il main di `regularizations.py` si può rimuovere, usiamo solo gli unit test per testare, che dici?

- il parametro `w` delle regularizations, di che dimensioni dev'essere? Solo un vettore o anche una matrice? Perché deve fare la "somma" di tutti i pesi di tutti i layer

2020-12-27 10:56 UTC, gaetanoantonicchio commented on src/unit_tests/test_regularizations.py
> +        np.testing.assert_array_almost_equal(regularization['l1'].deriv(w, lambd=lambd), l1_deriv)
non avevo messo il test sulla deriv di l1 perchè volevo un pò rivedere il codice. Perchè non sono sicuro che funzioni con matrici.

2020-12-27 10:57 UTC, gaetanoantonicchio commented on src/unit_tests/test_regularizations.py
> +        np.testing.assert_array_almost_equal(regularization['l1'].deriv(w, lambd=lambd), l1_deriv)
non avevo incluso il test sulla deriv di l1 perchè volevo rivedere un pò il codice. Funziona con vettori, ma non sono sicuro funzioni per matrici.

2020-12-27 11:01 UTC, AlexPasqua requested changes
Bisogna comunque testare il ValueError, non commentarlo.
Non so invece perché il `self.assertRaises(KeyError, regularization['nonexistent_reg'].func, self.w, lambd=0.1)` non funzioni

2021-01-04 15:31 UTC, merged